### ISSUE TITLE
Adding actions fails in repl.it Node environment

### ISSUE THREAD

**Issue by mkucharz** [mobxjs/mobx-state-tree#1096]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://repl.it/repls/GlamorousSphericalInterpreter

**Describe the expected behavior**
My model definition should work in the same way as in browser environment.

**Describe the observed behavior**
I think my actions are defined properly, but I'm still getting an exception. It looks like `isPlainObject()`  fails in Node env for some reason.

**Comment by Idered** [comment]
@xaviergonz 
```
Error: [mobx-state-tree] actions initializer should return a plain object containing actions
    at fail (/home/runner/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2606:11)
    at ModelType$$1.instantiateActions (/home/runner/node_modules/mobx-state-tree/dist/mobx-state-tree.js:3769:13)
    at actionInitializer (/home/runner/node_modules/mobx-state-tree/dist/mobx-state-tree.js:3761:19)
    at /home/runner/node_modules/mobx-state-tree/dist/mobx-state-tree.js:3917:63
    at Array.reduce (<anonymous>)
    at ModelType$$1.finalizeNewInstance (/home/runner/node_modules/mobx-state-tree/dist/mobx-state-tree.js:3917:27)
    at ObjectNode$$1._createObservableInstance (/home/runner/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1101:18)
    at executeAction$$1 (/home/runner/node_modules/mobx/lib/mobx.js:578:19)
    at ObjectNode$$1.res (/home/runner/node_modules/mobx/lib/mobx.js:570:16)
    at ObjectNode$$1.createObservableInstanceIfNeeded (/home/runner/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1201:18)
```

**Comment by k-g-a** [comment]
Try convert addTodo from arrow function into a simple addTodo() {...}

**Comment by xaviergonz** [comment]
Maybe it is an issue with repl.it? When it is  run there it fails, but I just tried that same code on my local machine (node 11 though) and it worked

**Comment by mkucharz** [comment]
@xaviergonz hmm, I checked it on my laptop (mac os, node 8.14, 10.4 and 11.3.) and it works. I'll check more environments. 

I'm not sure if conceptually `isPlainObject` is done right:
```js
function isPlainObject(value) {
    if (value === null || typeof value !== "object")
        return false;
    var proto = Object.getPrototypeOf(value);
    return proto === Object.prototype || proto === null;
```
I guess intention here is to verify if the object is a plain object, but in the last line there is equality comparison which is failing because it looks like prototype is not 100% equal (and I'm not sure if it always should be 100% equal?).

**Comment by xaviergonz** [comment]
I guess the code comes from here
https://stackoverflow.com/questions/5876332/how-can-i-differentiate-between-an-object-literal-other-javascript-objects
Not sure why repl.it would be mangling with object prototype chain though

**Comment by mkucharz** [comment]
@xaviergonz I think it is not only repl.it thing. I faced it for the first time in one of the popular Docker images with node env. I'll get back with more info.
