### ISSUE TITLE
Changing state from `action`  throws

### ISSUE THREAD

**Issue by safareli** [mobxjs/mobx-state-tree#1585]
I expect that I could do this, and it should work

```js
import { types } from "mobx-state-tree";
import { action, configure, observable } from "mobx";

configure({ enforceActions: "always" })

export const model = types.model("Item", {
  content: types.string,
})

export const setContent = action("setContent", (item, content) => {
  item.content = content
})



const item = model.create({content:""})
const item2 = observable({content:"as"})
console.log(item, item2)

// this works just fine
setContent(item2, "asdasd")

// this fails
setContent(item, "asdasd")
```

but when calling setContent, I get:

```
Error: [mobx-state-tree] Cannot modify 'Item@<root>', the object is protected and can only be modified by using an action.
    at fail$1 (https://9t7j9.csb.app/node_modules/mobx-state-tree/dist/mobx-state-tree.module.js:2704:10)
    at ObjectNode.assertWritable (https://9t7j9.csb.app/node_modules/mobx-state-tree/dist/mobx-state-tree.module.js:1575:13)
    at Array.ModelType.willChange (https://9t7j9.csb.app/node_modules/mobx-state-tree/dist/mobx-state-tree.module.js:4067:10)
    at interceptChange (https://9t7j9.csb.app/node_modules/mobx/lib/mobx.module.js:2810:31)
    at ObservableObjectAdministration.write (https://9t7j9.csb.app/node_modules/mobx/lib/mobx.module.js:3836:20)
    at Object.set [as content] (https://9t7j9.csb.app/node_modules/mobx/lib/mobx.module.js:4024:19)
    at eval (https://9t7j9.csb.app/index.js:17:16)
    at executeAction (https://9t7j9.csb.app/node_modules/mobx/lib/mobx.module.js:1171:15)
    at setContent (https://9t7j9.csb.app/node_modules/mobx/lib/mobx.module.js:1156:12)
    at evaluate (https://9t7j9.csb.app/index.js:22:1)
    at z (https://codesandbox.io/static/js/sandbox.ac6a13f34.js:1:97548)
    at Q.evaluate (https://codesandbox.io/static/js/sandbox.ac6a13f34.js:1:109662)
    at me.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.ac6a13f34.js:1:119233)
    at me.evaluateModule (https://codesandbox.io/static/js/sandbox.ac6a13f34.js:1:118969)
    at https://codesandbox.io/static/js/sandbox.ac6a13f34.js:1:800938
    at l (https://codesandbox.io/static/js/common-sandbox.43541997b.chunk.js:1:256735)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.43541997b.chunk.js:1:256488)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.43541997b.chunk.js:1:257092)
    at t (https://codesandbox.io/static/js/common-sandbox.43541997b.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.43541997b.chunk.js:1:2616)
```

sandbox : https://codesandbox.io/embed/mobx-state-change-action-czfvp?file=/index.js

I know about the actions method on model but I want to execute mutating action defined outside of the actions. Is there something I can do for that? or am i using `action` incorrectly?

(https://spectrum.chat/mobx-state-tree/general/change-state-from-action-throws~b4d521d9-b1f3-45b8-aa9a-52b756164d3e)

**Comment by mweststrate** [comment]
Yes, you cannot update mst models directly from mobx action, but should
defining actions on your model instead to update things.

**Comment by safareli** [comment]
What's the reason behind that? can "making regular mobx actions work fine with MST objects" be a valid feature request?

For future reader this hack might be helpful;
```ts
someMSTmodel
  .actions((self) => ({
    __run: <T>(f: () => T): T => f(),
  }));


type HasRun = {__run: <T>(f: () => T) => T }
const action = <T extends Array<unknown>, S extends HasRun, R>(
  func: (self: S, ...args: T) => R
) => {
  return (self: S, ...args: T): R => {
    return self.__run(() => func(self, ...args));
  };
};
```

**Comment by mweststrate** [comment]
The explanation and solution are both literally in the docs.

**Comment by safareli** [comment]
can you give the link? I did read docs and couldn't find explanation of why mobx action don't work on mst objects. 

I know that I should use `.actions` on the model, but TypeScript typing is problematic and to avoid typing issues I wanted to define actions in the top level.
