### ISSUE TITLE
TypeError: adm.raw is not a function in React Native with TypeScript

### ISSUE THREAD

**Issue by dawidp9** [mobxjs/mobx-state-tree#1725]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions)

Hi, when trying to add mobx state tree with mobx react lite to a React Native CLI empty project (generated with cra) with TypeScript I'm getting a runtime error after an app started with the message `TypeError: adm.raw is not a function. (In 'adm.raw()', 'adm.raw' is undefined)`. Full error log is below:  
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: adm.raw is not a function. (In 'adm.raw()', 'adm.raw' is undefined)
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123654:32
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123642:38
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123773:20
forEach@[native code]
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123772:35
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123641:25
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119688:77
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119762:53
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119044:26
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119758:34
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119470:30
executeAction@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113471:22
res@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113451:27
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119405:42
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:120289:46
get@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:118895:34
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:120178:65
executeAction@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113471:22
res@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113451:27
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:120281:44
executeAction@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113471:22
res@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113451:27
setupAppStore$@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:117958:49
tryCatch@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28650:23
invoke@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28823:32
tryCatch@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28650:23
invoke@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28723:30
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28733:21
tryCallOne@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:3419:16
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:3520:27
_callTimer@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:30679:17
_callImmediatesPass@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:30718:17
callImmediates@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:30935:33
__callImmediates@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:2707:35
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:2493:34
__guard@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:2690:15
flushedQueue@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:2492:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
```
 This is how my dependencies look's like: 
```
 "dependencies": {
    "mobx": "5.15.7",
    "mobx-react-lite": "2.2.2",
    "mobx-state-tree": "^5.0.1",
    "react": "16.13.1",
    "react-native": "0.63.3",
     ...
  },
```
It's my root store: 
```
import {types, Instance} from 'mobx-state-tree';

const RootStore = types
  .model('RootStore', {
    isReady: types.optional(types.boolean, false),
  })
  .actions((self) => {
    return {
      setReady(booleanState: boolean) {
        self.isReady = booleanState;
      },
    };
  });

export type RootStoreModel = Instance<typeof RootStore>;
export default RootStore;
```
My setupRootStore method: 
```
const setupRootStore = async (): Promise<RootStoreModel> => {
  const env = await createEnvironment();
  return RootStore.create({}, env);
};
```
This is how I create Context: 
```
const StoreContext = createContext<RootStoreModel>({} as RootStoreModel);
```
And my entry point `App.tsx` where I initialise the store and provide the context looks like this: 
```
const App: React.FC = () => {
 const [rootStore, setRootStore] = useState<RootStoreModel | null>(null);

  useEffect(() => {
    (async () => {
      setRootStore(await setupRootStore());
    })();
  }, []);

  if (!rootStore) return null;

  return (
    <StoreContext.Provider value={rootStore}>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView>
          <Welcome />
        </ScrollView>
      </SafeAreaView>
    </StoreContext.Provider>
  );
}
```

What could cause such an error? Am I missing something? 
Thank you in advance for your answers

**Comment by jamonholmgren** [comment]
@dawidp9 Would you mind providing a repo with the above setup for me to clone down and try?

**Comment by pengchengbuaa** [comment]
facing same issue

**Comment by mogarick** [comment]
@jamonholmgren  @dawidp9 @pengchengbuaa I got the same error but  in my case it occurred because I was accidentally declaring a Model prop and a computed getter of the same name and that caused Mobx collapsed.

Here's the code fragment for the mode type
``` javascript
types
      .model({
        id: types.identifier,
        name: types.string,
        lastName: types.maybeNull(types.string),
        fullName: types.string,
        contactInfo: types.array(ParticipantDogRelatedPersonContactItem),
      })
      .views((self) => ({
        get fullName() {
          return `${
            self.lastName ? `${self.name} ${self.lastName}` : `${self.name}`
          }`;
        },
      }))
  )
```

Here is the error log I was getting
```
TypeError: adm.raw is not a function

      at ModelType.value (node_modules/mobx-state-tree/dist/mobx-state-tree.js:6165:33)
      at node_modules/mobx-state-tree/dist/mobx-state-tree.js:6152:32
      at node_modules/mobx-state-tree/dist/mobx-state-tree.js:6274:64
          at Array.forEach (<anonymous>)
      at ModelType.value (node_modules/mobx-state-tree/dist/mobx-state-tree.js:6274:32)
      at ModelType.value (node_modules/mobx-state-tree/dist/mobx-state-tree.js:6151:18)
      at ObjectNode.value (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1876:33)
      at ObjectNode.value (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2024:18)
      at node_modules/mobx-state-tree/dist/mobx-state-tree.js:2025:22
          at Array.forEach (<anonymous>)
```

Here is the code fragment from mob-state.tree.js where it occurred:
``` javascript
Object.defineProperty(ModelType.prototype, "getChildNode", {
        enumerable: false,
        configurable: true,
        writable: true,
        value: function (node, key) {
            if (!(key in this.properties))
                throw fail$1("Not a value property: " + key);
            var adm = mobx._getAdministration(node.storedValue, key);
            var childNode = adm.raw();
            if (!childNode)
                throw fail$1("Node not available for property " + key);
            return childNode;
        }
    });

```
So the problem occurs when `adm` got a value that didn't include `raw` as function. I don't know why `adm` got a value if something got wrong but the error was thrown because of that.

Now, adding a log point to trace the values for `key` and `node` gave me the hint about the error being on `fullName` as a computed value.

Heres is the trace log point definition I used:

```
 node.name={node.type.name}, Key= {key}, Properties={node.type.properties}, node.storedValue={node.storedValue}, node._snapshotComputed.value_={node._snapshotComputed.value_}
```
And here is the output for the Node where the prop `fullName` was doubling both as prop and as computed getter.

```
node.name='ParticipantDogRelatedPersonPerson', Key= 'fullName', Properties={
      id: IdentifierType {
        C: undefined,
        S: undefined,
        T: undefined,
        N: undefined,
        isType: true,
        name: 'identifier',
        validType: 'string',
        flags: 2048,
        [Symbol($type)]: undefined
      },
      name: CoreType {
        C: undefined,
        S: undefined,
        T: undefined,
        N: undefined,
        isType: true,
        name: 'string',
        flags: 1,
        checker: [Function (anonymous)],
        initializer: [Function: identity],
        [Symbol($type)]: undefined
      },
      lastName: Union {
        C: undefined,
        S: undefined,
        T: undefined,
        N: undefined,
        isType: true,
        name: '(string | null)',
        _types: [ [CoreType], [OptionalValue] ],
        _dispatcher: undefined,
        _eager: true,
        [Symbol($type)]: undefined
      },
      fullName: CoreType {
        C: undefined,
        S: undefined,
        T: undefined,
        N: undefined,
        isType: true,
        name: 'string',
        flags: 1,
        checker: [Function (anonymous)],
        initializer: [Function: identity],
        [Symbol($type)]: undefined
      },
      contactInfo: OptionalValue {
        C: undefined,
        S: undefined,
        T: undefined,
        N: undefined,
        isType: true,
        name: 'ParticipantDogRelatedPersonContactItem[]',
        _subtype: ArrayType {
          C: undefined,
          S: undefined,
          T: undefined,
          N: undefined,
          isType: true,
          name: 'ParticipantDogRelatedPersonContactItem[]',
          identifierAttribute: undefined,
          _subType: [ModelType],
          flags: 32,
          hookInitializers: [],
          [Symbol($type)]: undefined
        },
        _defaultValue: [],
        optionalValues: [ undefined ],
        [Symbol($type)]: undefined
      }
    }, node.storedValue={
      id: [Getter/Setter],
      name: [Getter/Setter],
      lastName: [Getter/Setter],
      contactInfo: [Getter/Setter],
      lastSnapshot: [Getter/Setter],
      dataStoreSyncState: [Getter/Setter],
      dataStoreSyncStateDate: [Getter/Setter],
      graphQLStoreSyncState: [Getter/Setter],
      graphQLStoreSyncStateDate: [Getter/Setter]
    }, node._snapshotComputed.value_=CaughtException {
      cause: TypeError: mobx.getAtom(...).reportObserved is not a function
          at /<path>/node_modules/mobx-state-tree/dist/mobx-state-tree.js:6180:54
          at /<path>/node_modules/mobx-state-tree/dist/mobx-state-tree.js:6274:64
          at Array.forEach (<anonymous>)
          at ModelType.value (/<path>/node_modules/mobx-state-tree/dist/mobx-state-tree.js:6274:32)
          at ModelType.value (/<path>/node_modules/mobx-state-tree/dist/mobx-state-tree.js:6179:18)
          at ObjectNode.value (/<path>/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1779:30)
          at ObjectNode.value (/<path>/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1770:24)
          at call (/<path>/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1524:83)
          at trackDerivedFunction (/<path>/node_modules/mobx/src/core/derivation.ts:177:24)
          at ComputedValue.computeValue_ (/<path>/node_modules/mobx/src/core/computedvalue.ts:237:19)
    }

```

As I didn't dig much more on understanding the inners of the lib I don't get why `node.storedValue` doesn't include `fullName` but `node.type.properties` doesn't. But when I saw 
```
node._snapshotComputed.value_=CaughtException {
      cause: TypeError: mobx.getAtom(...).reportObserved is not a function
``` 
I remembered that I've aready declared a computed value with the same name that a prop I've just added because it wasn't being included in the snapshots (I didn't remember snapshots don't include computed values duh).

So maybe this long post helps anybody to find the possible cause of this error.

It would be nice if MST and/or Mobx could give a more clear hint about the possible reason of errors like this. 
In my particular case, I don't know if there could be a way for the lib to throw an error telling me I have declared a model prop with the same name as a view getter.

**Comment by yulolimum** [comment]
Same issue here. 

I had both a `props` and a `views` item with the same name. Mine was a bit tougher to debug since the offending computed view was inside an `extend`. 

+1 on the suggestion for a more helpful error.

**Comment by ryskin** [comment]
Yes, need this hint ) the last comment helped me to find a mistake after 1-hour investigation.

**Comment by jamonholmgren** [comment]
Would love some help with a PR for a more friendly error message!

**Comment by jamonholmgren** [comment]
Here's a minimal repro for anyone wanting to tackle this.

https://codesandbox.io/s/dry-pond-zhecyw?file=/src/index.ts

**Comment by coolsoftwaretyler** [comment]
Ooh yes, I ran into this recently as well. We had a property and a computed value in a big model that was hard to troubleshoot.

I'm going to tag this issue for PR welcome/enhancement/easy (I think, at least, haha).

**Comment by coolsoftwaretyler** [comment]
Thanks @chakrihacker! I will assign it to you. Please tag me in your PR for review. Thanks!

**Comment by sambisou** [comment]
Hello everyone,
Do you know when this fix will be integrated in the npm package? Would that be part of 5.2 or till 5.1.8?
Thanks

**Comment by coolsoftwaretyler** [comment]
Hey @sambisou - I expect we'll have another release candidate that includes this fix for 5.2.0 over the coming weekend. I'll make a post about it in discussions.

We have a few things to clean up in the next couple of days, but keep an eye on discussins or the npm page.

Once that release candidate has some time for feedback, we'll ship and mark it as latest. Maybe a week or two after. But I'll personally be using that RC in production next week.

**Comment by coolsoftwaretyler** [comment]
Hey @sambisou - there's a release candidate on npm that makes it available. Try 5.2.0-alpha.2.

I think the update is pretty stable and I plan to use it in production, but if you want to wait for it to be marked as stable, I expect to do that around September 8.

**Comment by sambisou** [comment]
@coolsoftwaretyler thank you so much for your quick feedback. I will try it out right away :-)
