### ISSUE TITLE
put() method throws error when using numeric id for types.identifier

### ISSUE THREAD

**Issue by qaiser110** [mobxjs/mobx-state-tree#336]
I'm already using mobx. __mobx-state-tree__ looks great and I would like to use it, but I'm facing an issue.

I have numeric id's being fetched from the api. So I've defined numeric id defined in my model via types.identifier, like this:

```js
import { types } from "mobx-state-tree"

const Quote = types.model("Quote", {
  id: types.identifier(types.refinement(types.number)),
  title: types.string,
})

const QteStore = types
  .model("QteStore", {
    quotes: types.maybe(types.map(Quote), {}),
  })
  .actions(self => {
    function loadQuotes(quotes) {
      quotes.forEach(quote => {
        self.quotes.put(quote)
      });
    }

    return { loadQuotes }
  })

let qtes = [{
  id: 1,
  title: 'a title',
}]

const store = QteStore.create({quotes: {}})
store.loadQuotes(qtes)
```

But my `loadQuotes` action throws this error when I use `self.quotes.put()`:

```js
    TypeError: Cannot read property 'validate' of undefined
      
      at Refinement.Object.<anonymous>.Refinement.isValidSnapshot (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2912:38)
      at Refinement.Object.<anonymous>.ComplexType.validate (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1480:21)
      at IdentifierType.Object.<anonymous>.IdentifierType.isValidSnapshot (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2174:40)
      at IdentifierType.Object.<anonymous>.ComplexType.validate (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1480:21)
      at node_modules/mobx-state-tree/dist/mobx-state-tree.js:2537:42
      at Array.map (native)
      at ObjectType.Object.<anonymous>.ObjectType.isValidSnapshot (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2536:55)
      at ObjectType.Object.<anonymous>.ComplexType.validate (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1480:21)
      at typecheck (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1450:23)
      at ObjectType.Object.<anonymous>.ComplexType.create (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1467:9)
      at executeAction (node_modules/mobx/lib/mobx.js:867:19)
      at ObjectType.res (node_modules/mobx/lib/mobx.js:858:16)
      at ObservableMap.put (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1590:44)
      at common/quote/store.test.js:42:19
      at Array.forEach (native)
      at Object.loadQuotes (common/quote/store.test.js:41:12)
      at runMiddleWares (node_modules/mobx-state-tree/dist/mobx-state-tree.js:270:27)
      at runWithActionContext (node_modules/mobx-state-tree/dist/mobx-state-tree.js:231:16)
      at Object.<anonymous> (node_modules/mobx-state-tree/dist/mobx-state-tree.js:246:16)
      at executeAction (node_modules/mobx/lib/mobx.js:867:19)
      at Object.res (node_modules/mobx/lib/mobx.js:858:16)
      at Object.<anonymous> (common/quote/store.test.js:56:9)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

The only way I can get this to work is using assigning values as `self.quotes[quote.id] = quote`:

```js
function loadQuotes(quotes) {
      quotes.forEach(quote => {
        self.quotes[quote.id] = quote
      });
    }
```

So I have a few questions:

- If this a bug in  [put() method](https://github.com/mobxjs/mobx-state-tree/blob/e9307f7b65c32d706f00d37ec7b5e8429170143b/src/types/complex-types/map.ts#L44-L62)
- Would assigning values as `self.quotes[quote.id] = quote` cause issues with referencing the store items by id
- Is there a better / recommended way of doing this

**Comment by mattiamanzati** [comment]
Ok, so first of all the error is thrown because you are using refinement with wrong parameters, once #328 will get merged, youll receive proper warnings for that.
` types.identifier(types.refinement(types.number)),`
should be
` types.identifier(types.number),`.

> Would assigning values as self.quotes[quote.id] = quote cause issues with referencing the store items by id

You can't do self.quotes[quote.id] = quote because self.quote is a ES6 Map, so you need self.quotes.set(quote.id, quote)

> Is there a better / recommended way of doing this

No, its perfectly fine :)

**Comment by qaiser110** [comment]
Thank you @mattiamanzati  

I did try `self.quotes.set(quote.id, quote)` but didn't realize that the errors thrown were due to a required type missing from the model. And removing set() falsely fixed it.

Thank you for the awesome work!!
