### ISSUE TITLE
[mobx-state-tree] expected first argument to be a mobx-state-tree node

### ISSUE THREAD

**Issue by mydearxym** [mobxjs/mobx-state-tree#366]
in my typescript project , define those are fine:

```js
const ShopStore = types.model('ShopStore', {
  page: 'hello',
  selectedBookId: '',
})
```

```js
const ShopStore = types.model('ShopStore', {
  page: 'hello',
  selectedBookId: '',
  get hello() {
    return false //getEnv(this).alert
  },
})
```

```js
const ShopStore = types.model('ShopStore', {
  page: 'hello',
  selectedBookId: '',
  get hello() {
    return this.page
  },
})
```

but once use getEnv(this)
```js
const ShopStore = types.model('ShopStore', {
  page: 'hello',
  selectedBookId: '',
  get alert() {
    return getEnv(this).alert
  },
})
```

```bash
Error: [mobx-state-tree] expected first argument to be a mobx-state-tree node, got [object Object] instead
    at fail (/Users/xieyiming/code/mastani/node_modules/mobx-state-tree/dist/mobx-state-tree.js:48:11)
    at getEnv (/Users/xieyiming/code/mastani/node_modules/mobx-state-tree/dist/mobx-state-tree.js:823:13)
    at Object.get alert [as alert] (/Users/xieyiming/code/mastani/stores/rootStore.js:17:16)
    at Function.assign (<anonymous>)
    at /Users/xieyiming/code/mastani/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2395:27
    at Array.reduce (<anonymous>)
    at toPropertiesObject (/Users/xieyiming/code/mastani/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2379:36)
    at new ObjectType (/Users/xieyiming/code/mastani/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2457:28)
    at Object.model (/Users/xieyiming/code/mastani/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2672:12)
    at Object.<anonymous> (/Users/xieyiming/code/mastani/stores/rootStore.js:13:19)
```

i am confused ..

**Comment by mattiamanzati** [comment]
Since 0.10 you need to define views in a separate section

```
const ShopStore = types.model('ShopStore', {
  page: 'hello',
  selectedBookId: ''
}).views(self =>({
  get alert() {
    return getEnv(self).alert
  },
})
```

**Comment by luisherranz** [comment]
Computed values are now defined in `views` instead of `props` and you should use `self` instead of `this` as well:

```javascript
const ShopStore = types.model('ShopStore', {
    page: 'hello',
    selectedBookId: '',
  },
}).views(self => ({
  get alert() {
    return getEnv(self).alert
  },
});
```

**Comment by luisherranz** [comment]
you beat me 😆

**Comment by mydearxym** [comment]
@mattiamanzati  @luisherranz   thanks for quick reply.  i was using the old version example

**Comment by Godofbrowser** [comment]
This error 

> Error: [mobx-state-tree] expected first argument to be a mobx-state-tree node, got instead

can also be cause by cyclic dependencies as it was in my case... limiting the use of barrel files might help
