### ISSUE TITLE
Unable to create a model from snapshot.

### ISSUE THREAD

**Issue by tylerlong** [mobxjs/mobx-state-tree#482]
Source code is here: https://github.com/tylerlong/OpenAPI-Editor

You can run it by:

```
yarn install
yarn dev
open http://localhost:8080
```

I will describe the problem here:

### OpenAPI.js
```js
import { types } from 'mobx-state-tree'

import Info from './Info'

const OpenAPI = types.model({
  openapi: '3.0.0',
  info: types.reference(Info)
}).actions(self => ({
  update (key, value) {
    self[key] = value
  }
}))

export default OpenAPI
```

### Info.js
```js
import { types } from 'mobx-state-tree'

const Info = types.model({
  id: types.identifier(types.string),
  title: '',
  description: '',
  termsOfService: '',
  version: ''
}).actions(self => ({
  update (key, value) {
    self[key] = value
  }
}))

export default Info
```

### index.js
```js
const openapi = OpenAPI.create({
  openapi: '3.0.0',
  info: {
    id: 'info',
    title: '',
    description: '',
    termsOfService: '',
    version: ''
  }
})
```

## Error message

```
mobx-state-tree.module.js:44 Uncaught Error: [mobx-state-tree] Error while converting `{"openapi":"3.0.0","info":{"id":"info","title":"","description":"","termsOfService":"","version":""}}` to `AnonymousModel`:
at path "/info" snapshot `{"id":"info","title":"","description":"","termsOfService":"","version":""}` is not assignable to type: `reference(AnonymousModel)` (Value is not a valid identifier, which is a string or a number), expected an instance of `reference(AnonymousModel)` or a snapshot like `reference(AnonymousModel)` instead.
    at fail (http://localhost:8080/index.bundle.js:4235:11)
    at typecheckPublic (http://localhost:8080/index.bundle.js:5724:9)
    at typecheck (http://localhost:8080/index.bundle.js:5709:5)
    at ObjectType.ComplexType.create (http://localhost:8080/index.bundle.js:5739:9)
    at executeAction (http://localhost:8080/index.bundle.js:13103:19)
    at ObjectType.res (http://localhost:8080/index.bundle.js:13094:16)
    at Object.<anonymous> (http://localhost:8080/index.bundle.js:30051:33)
    at __webpack_require__ (http://localhost:8080/index.bundle.js:20:30)
    at Object.<anonymous> (http://localhost:8080/index.bundle.js:15839:18)
    at __webpack_require__ (http://localhost:8080/index.bundle.js:20:30)
```

The error message is not very clear to me and I don't understand what is wrong with my code.

Help neeeded. Thank you in advance.

**Comment by mattiamanzati** [comment]
The reference type will put in the snapshot just the model ID and expect the model you are referencing to live somewhere else. Try removing types.reference, maybe you misunderstood what a reference is :)

const OpenAPI = types.model({
  openapi: '3.0.0',
  info: Info
}).actions(self => ({
  update (key, value) {
    self[key] = value
  }
}))

export default OpenAPI

**Comment by tylerlong** [comment]
I have figured it out myself.

```js
const { types } = require('mobx-state-tree')

const Info = types.model({
  title: ''
})

const OpenAPI = types.model({
  openapi: '',
  info: Info
})

const openAPI = OpenAPI.create({
  openapi: '3.0.0',
  info: {
    title: 'Hello world'
  }
})

console.log(openAPI.openapi)
console.log(openAPI.info.title)
```


## the following works

```js
const OpenAPI = types.model({
  openapi: '',
  info: Info
})
```


## the following doesn't work

```js
const OpenAPI = types.model({
  openapi: '',
  info: types.reference(Info)
})
```

Could anybody explain?

**Comment by tylerlong** [comment]
Update: I didn't refresh the page and I didn't see @mattiamanzati's response.

Close it now.

**Comment by mattiamanzati** [comment]
The reference type will put in the snapshot just the model ID and expect the model you are referencing to live somewhere else. 
An example is if you have a list of users and a list of todos and want to add for each todo a reference to its assignee user. (see the getting started guide)
The latter method, without reference, is telling MST to expect data shaped as an Info object, so it will do what you are trying to achieve.
Feel free to reopen for any other question :)
