### ISSUE TITLE
Composing `Model.create` throws TypeError: type.validate is not a function

### ISSUE THREAD

**Issue by levithomason** [mobxjs/mobx-state-tree#508]
I use function composure quite a bit.  In this case, I have some `propertyData` that I'd like to pass to `propertyInfoToAnalysis()`, then `crunch()`, then `Analysis.create()` (MST model).

### TypeError: type.validate is not a function

```js
import _ from 'lodash/fp'
import { propertyInfoToAnalysis, crunch } from 'rei'

const Analysis = types.model({ /* flat object of bools, strings, numbers */ })
const propertyDetails = { /* data to be reshaped into an Analysis */ }

_.flow(
  propertyInfoToAnalysis,
  crunch,
  Analysis.create
(propertyDetails)
// => TypeError: type.validate is not a function
```

Also when using a vanilla custom `compose()`:

```js
const compose = (first, ...rest) => data => rest.reduce((x, fn) => fn(x), first(data))

compose(
  propertyInfoToAnalysis,
  crunch,
  Analysis.create
(propertyDetails)
// => TypeError: type.validate is not a function
```

### Works

Passing a value directly to `Analysis.create` works 😕 

```js
Analysis.create(_.flow(propertyInfoToAnalysis, crunch)(propertyDetails))

// or

Analysis.create(crunch(propertyInfoToAnalysis(propertyDetails)))
```

***

There must be some magic involved with how `create()` it is called?  Apologies if it is in the docs and I just couldn't find it.  Else, any insight?

**Comment by levithomason** [comment]
A stack trace might be of help:

```
node_modules/mobx-state-tree/dist/mobx-state-tree.js:1567
    var errors = type.validate(value, [{ path: "", type: type }]);
                     ^

TypeError: Cannot read property 'validate' of undefined
    at typecheckPublic (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1567:22)
    at typecheck (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1554:5)
    at ComplexType.create (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1584:9)
    at executeAction (node_modules/mobx/lib/mobx.js:915:19)
    at res (node_modules/mobx/lib/mobx.js:906:16)
    at rest.reduce (src/common/models/Analysis.js:485:70)
    at Array.reduce (native)
    at data (src/common/models/Analysis.js:485:50)
    at Object.<anonymous> (src/common/models/Analysis.js:491:1)
    at Module._compile (module.js:569:30)
```

**Comment by mattiamanzati** [comment]
That error usually happens when one of the prop of the model is'nt a "types."something, can you please check that? :)

**Comment by levithomason** [comment]
I believe they were all values of `types`.  I cannot verify as I switched to vanilla mobx.  I was having difficulty with MST.  I may try it out again at a later date, once the other perf issues are also addressed.

Thanks for the work and help anyhow.
