### ISSUE TITLE
[Question]adding to array types

### ISSUE THREAD

**Issue by andrusek** [mobxjs/mobx-state-tree#565]
Hi not sure if this is the right place for this kind of question (sorry if it is not).  I am new to mobx state tree and I am attempting to create a store that has an array of other store objects.  For example:

const CJobObjectStore = types.model("CJobObjectStore",{
	jobSteps: types.optional(types.array(JobStepDefinitionObjectStore), []) ,
	sequencing: types.optional(types.enumeration("State", ["parallel", "sequential"]), 'sequential'),
	options: types.optional(types.array(JobOption), [JobOption.create({name:'continueOnError', type: 'boolean', value: true})]) 
})..actions(self => {
	
	function addJobStep(id, type){
		let lastDisplaySeq;
		if (self.hasJobSteps) {
			lastDisplaySeq = self.jobSteps[self.jobSteps.length - 1];
		} else {
			lastDisplaySeq = -1;
		}	
		
		
	self.jobSteps.push({
			stepObject: JobStepDefinition.create({
				id: id,
				type: type
			}),
			displaySequence: lastDisplaySeq + 1
		}); 
	}
	
    return {
        addJobStep
        
    }
    
});

But when the addJobStep action is called I get this kind of error:

  TypeError: Cannot read property 'length' of undefined
      
      at typecheckPublic$$1 (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1682:15)
      at typecheck$$1 (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1668:5)
      at valueAsNode (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2540:5)
      at reconcileArrayChildren (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2516:35)
      at ArrayType$$1.willChange (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2373:32)
      at Array.<anonymous> (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2339:71)
      at interceptChange (node_modules/mobx/lib/mobx.js:131:41)
      at ObservableArrayAdministration.spliceWithArray (node_modules/mobx/lib/mobx.js:369:26)
      at ObservableArray.push (node_modules/mobx/lib/mobx.js:546:13)
      at addJobStep (src/admin-components/stores/JobObjectStore.js:57:17)
      at executeAction (node_modules/mobx/lib/mobx.js:915:19)
      at res (node_modules/mobx/lib/mobx.js:906:16)
      at runNextMiddleware (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1604:31)
      at onActionMiddleware (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1490:20)
      at runNextMiddleware (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1602:20)
      at runMiddleWares (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1606:12)
      at runWithActionContext$$1 (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1507:16)
      at Object.<anonymous> (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1524:16)

It seems unhappy with the 
self.jobSteps.push({
			stepObject: JobStepDefinition.create({
				id: id,
				type: type
			}),
			displaySequence: lastDisplaySeq + 1
		}); 

any thoughts on what I might be doing wrong would be greatly appreciated

**Comment by andrusek** [comment]
never mind it was my error
