### ISSUE TITLE
Version 1.3.1 not compatible with mobx v4.0.0?

### ISSUE THREAD

**Issue by botteu** [mobxjs/mobx-state-tree#697]
Getting errors while running tests when using v1.3.1 of mobx-state-tree and mobx v4.0.0 (which is what you get if you follow the installation instructions).

`console.error node_modules/mobx/lib/mobx.js:2645
      [mobx] Deprecated: 'observable.shallowObject', use 'observable.object(values, {}, { deep: false })' instead.

    TypeError: Cannot define property __mobxDidRunLazyInitializers, object is not extensible
        at Function.defineProperty (<anonymous>)

      at addHiddenProp (node_modules/mobx/lib/mobx.js:2685:12)
      at initializeInstance (node_modules/mobx/lib/mobx.js:100:5)
      at isObservableObject (node_modules/mobx/lib/mobx.js:1248:9)
      at _isObservable (node_modules/mobx/lib/mobx.js:1290:13)
      at isObservable (node_modules/mobx/lib/mobx.js:1300:12)
      at extendObservable (node_modules/mobx/lib/mobx.js:1377:20)
      at Function.object (node_modules/mobx/lib/mobx.js:1518:16)
      at Function.shallowObject (node_modules/mobx/lib/mobx.js:1524:27)
      at ModelType$$1._this.createNewInstance (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2749:44)
      at createNode$$1 (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1807:23)
      at ModelType$$1.Object.<anonymous>.ModelType$$1.instantiate (node_modules/mobx-state-tree/dist/mobx-state-tree.js:2926:16)
      at ModelType$$1.Object.<anonymous>.ComplexType$$1.create (node_modules/mobx-state-tree/dist/mobx-state-tree.js:1162:21)
      at executeAction (node_modules/mobx/lib/mobx.js:196:19)
      at ModelType$$1.res (node_modules/mobx/lib/mobx.js:188:16)
      at Object.<anonymous>.it (src/models/WishList.test.js:5:38)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>`

**Comment by robinfehr** [comment]
it's not yet compatible no. there is a PR in progress already.

**Comment by amsdamsgram** [comment]
Same here, with `yarn add mobx mobx-state-tree`, I got mobx 4 installed not 3.
I tried `yarn add mobx-state-tree mobx` but same results.

My version of yarn is 1.3.2 just in case!

**Comment by mweststrate** [comment]
Just tested, `npm` installs the wrong version, but does warn about it. Yarn doesn't even warn. Which is super weird as the package.json of MST clearly states that it needs MobX 3 :-/.

**Comment by amsdamsgram** [comment]
Arf :/
I got a warning when running `yarn start` on a `create-react-native-app` though

**Comment by botteu** [comment]
Yeah, I just wanted to give you a heads up :) Was going through the MST tutorial over at egghead.io <http://egghead.io/> and was getting all these errors right from the get go. 
Already loving MST though and congrats on hitting 4.0 for mobx! Great work.
