### ISSUE TITLE
IE 11 Issues

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx-state-tree#765]
Hi

I need to Support IE 11 and ran into this issue.

exception}	Object doesn't support property or method 'assign'
in mobx-state-tree.module.js

 ```
  var name = opts.name || defaultObjectOptions.name;
        // TODO: this test still needed?
        if (!/^\w[\w\d_]*$/.test(name))
            fail("Typename should be a valid identifier: " + name);
        **Object.assign(_this, defaultObjectOptions, opts);**
        // ensures that any default value gets converted to its related type
        _this.properties = toPropertiesObject(_this.properties);
        freeze(_this.properties); // make sure nobody messes with it
        return _this;
    }

stack "TypeError: Object doesn't support property or method 'assign'\n at ModelType$$1 (eval code:3080:9)\n at model$$1 (eval code:3349:5)\n at eval code (eval code:9:1)\n at ./src/stores/AppStore.js (http://localhost:8080/index_bundle.js:2136:1)\n at __webpack_require__ (http://localhost:8080/index_bundle.js:710:12)\n at fn (http://localhost:8080/index_bundle.js:95:13)\n at eval code (eval code:9:1)\n at ./src/stores/Stores.js (http://localhost:8080/index_bundle.js:2148:1)\n at __webpack_require__ (http://localhost:8080/index_bundle.js:710:12)\n at fn (http://localhost:8080/index_bundle.js:95:13)"
```

How can I resolve this issue or does Mobx-state-tree no support IE 11(if so please update your documentation to let people know unfortunately many people still have to support IE 11.)

**Comment by skellock** [comment]
A polyfill will be required.  Here's more details:

https://stackoverflow.com/questions/32148218/why-does-object-assign-require-a-polyfill-when-babel-loader-is-being-used

**Comment by chobo2** [comment]
Ok, that's what I thought, I just did not know if it is something that I can take care on my side or if it has to be done at the library level.

I found this: https://babeljs.io/docs/usage/polyfill/

Do you guys think this will be enough to get MST working fine?

**Comment by skellock** [comment]
I'm not sure on the complete list of polyfills required for IE 11 to emulate an es6 environment.  You're probably good with `babel-polyfill`, but that's me guessing.

Keep testing as you go.  When you find the list, maybe contribute back a doc PR for "Tips for working with IE 11".

👍

**Comment by chobo2** [comment]
Ok, I will generate a list and report back you guys in a couple weeks. I have no problem adding more polly fills I am just worried there will be something that can't be polly filled and it will lead to me having to figure out if I can go on with MST, but I guessing this happens it will be very early on as there is only so many functions.

**Comment by robinfehr** [comment]
please make sure to check how much the lib get's bloated by that - babel-polyfill is usually quite big and does not check whether the polyfill must be included or not.

another thing you could try is babel-preset-env and specify the target browser.

while there is that, also you should consider that mobx4 will be supported for the longer run (not including proxies for example, which would be an IE problem too) but mobx5 will include proxies and it will be included into MST too.

therefore we might want to consider a similar strategy...ideas welcome :)

Windows 10 will be mainstream supported until October 13, 2020, and the end of extended support is October 14, 2025. which means we'd have to maintain what ever strategy we go with for quite some time.

and then again - not sure if it's worth the pain.

maybe someone has a brilliant idea - buit i guess it might be easiest to advise the users who need IE11 to fork it and transpile it with the needed loaders.

**Comment by chobo2** [comment]
Well, sadly most companies still need to support IE as the user base usually using it is just so big. As more people switch to Windows 10, I think IE levels will go down as eventhough it has IE 11 on it, it is not the default browser(edge is) and if you know how to find and change your default browser to IE 11 your probably not going to be using edge or IE 11.

But for now 40% of all my companies web traffic is IE 11, so we can't ignore it (I wish we could I would like to use stuff like CSS 3 grid and not have to check IE 11 after every change to make sure it all works).

**Comment by xaviergonz** [comment]
Closing due to inactivity, @chobo2 feel free to reopen it if desired :)

**Comment by chobo2** [comment]
@xaviergonz 

Yea, this issue can be closed. It seems to be working great in IE 11 again!

**Comment by alex-shamshurin** [comment]
Now MST supports Mobx 6 - which supports IE11. So are there any update ?
